---
- name: This is a simple playbook to add users via the my_users var
  hosts: tag_ryans-stuff
  become: yes
  vars:
    my_users:
      - ryan
  tasks:
    - name: Add the specified users to the managed server
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ my_users }}"
    - name: Make sure the bin directory is present in the users home dir
      file:
        path: "/home/{{ item }}/bin"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0640
        state: directory
      loop: "{{ my_users }}"
...
